name: deploy_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - dill
  - joblib
  - mlflow
  - fastapi
  - uvicorn

